// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okwimslqbvgszjiqzorb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rd2ltc2xxYnZnc3pqaXF6b3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjU1MzQsImV4cCI6MjA2NTQwMTUzNH0.d62e3KuAT5brEQrsVLIcPSbmmRWOa5Ps73MSCfo-eP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);